config/routes.rb
Rails.application.routes.draw do
  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'

  get 'followers' => 'epicenter#followers'

  resources :tweets
  devise_for :users

  root 'epicenter#feed'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord

	#associations
has_many :tweet_tags
has_many :tweets, through: :tweet_tags
	
		
	end

app/models/tweet.rb
class Tweet < ApplicationRecord
	# associations
	belongs_to :user
	has_many :tweet_tags
	has_many :tags, through: :tweet_tags
	#validations
	validates :message, presence:true
	validates :message, length: { maximum: 280, too_long: "A tweet is only 280 characters, dumbass!" }
	#hooks
	before_validation :link_check, on: :create
	after_validation :apply_link, on: :create

	private

	def apply_link
		arr = self.message.split
		index = arr.map { |x| x.include? 'http' }.index(true)

		if index
			shortened_url = arr[index]
			arr[index] = "<a href='#{self.link}' target='_blank'>#{shortened_url}</a>"

		end

		self.message = arr.join(" ")
	end

	def link_check
		
		if self.message.include?('http://') || self.message.include?('https://')
			arr = self.message.split
			index = arr.map { |x| x.include? 'http' }.index(true)
			self.link = arr[index]
			if self.link.length > 23
				arr[index] = "#{arr[index][0..19]}..."
			end
			self.message = arr.join(' ')
		end
	end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord

#associations (pet name collar)
belongs_to :tweet 
belongs_to :tag


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # associations
  has_many :tweets
  # validations
  validates :username, presence: true
  validates :username, uniqueness: true

  serialize :following, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

before_action :authenticate_user!, except: [:show_user, :all_users]

def all_users
  @users = User.all 
end

def following
  @users = User.where(id: current_user.following)
end

def followers
  @users = []

  User.all.each do |user|
    if user.following.include?(current_user.id)
       @users.push(user)
        end
      end
  end

  def feed
  	@following_tweets = Tweet.where(user_id: current_user.following << current_user.id)
  end

  def show_user
  	@user = User.find(params[:id])
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end



  def now_following
  	current_user.following.push(params[:id].to_i)
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  end

  def unfollow
  	current_user.following.delete(params[:id].to_i)
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    message_arr = @tweet.message.split




    message_arr.each_with_index do |word, index|
      if word[0] == '#'
        tag = Tag.find_or_create_by(phrase: word)
        TweetTag.create(tweet_id: @tweet.id, tag_id: tag.id)
        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
    end
  end
    @tweet.update(message: message_arr.join(' '))

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/epicenter/_user_list.html.erb
<div class="row">
	<% @users.each do |user| %>
		<div class='col-md-4'>
			<div class="well">
				<h2><%= link_to user.username, show_user_path(id: user.id) %></h2>
				<h3><%= user.name %></h3>
				<p>
					<%= user.bio %>
				</p>
			</div>
		</div>
	<% end %>
</div>

app/views/epicenter/all_users.html.erb


<h1>All Users</h1>

<%= render 'user_list' %>


app/views/epicenter/feed.html.erb
<h1>The Feed of <%= current_user.username %></h1>
<h3>Here's what's goin' on...</h3>

<div class="row">
<div class="col-md-6 col-md-offset-3">


<% @following_tweets.each do |tweet| %>

<%= render tweet %>
<% end %>
</div>
</div>

app/views/epicenter/followers.html.erb


<h1> Your Followers </h1>
<%= render 'user_list' %>

app/views/epicenter/following.html.erb

<h1> Following </h1>

<%= render 'user_list' %>


app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<h1>The Profile of <%=  @user.username %></h1>

<div class="row">
	<div class="col-md-3">
		<div class="well">
			<p>
				Name: <%= @user.name %>
			</p>
			<p>
				Location: <%= @user.location %>
			</p>
			<p>
				Bio: <%= @user.bio %>
			</p>

		</div>

		<% if user_signed_in? && current_user != @user %>
			<% if current_user.following.include?(@user.id) %>
			<%= link_to 'Following', unfollow_path(id: @user.id), class: 'btn btn-primary', id: "unfollow-btn" %>
			<% else %>
			<%= link_to 'Follow', now_following_path(id: @user.id), class: 'btn btn-primary' %>
			<% end %>
		<% end %>
	</div>
	<div class="col-md-6">
		<% @user.tweets.each do |tweet| %>
		<%= render tweet %>
<% end %>

		
	</div>
</div>

app/views/epicenter/tag_tweets.html.erb

<h1>Showing Chirps with <%= @tag.phrase %></h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		
		<%= render @tag.tweets %> 
	</div>
</div>		

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Birdland</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-inverse">

  		<div class="navbar-header">
  			<%= link_to 'brldlnd', root_path, class: 'navbar-brand' %>
		</div>
		<ul class="nav navbar-nav">
			<li>
				<%= link_to 'All Users', all_users_path %>
			</li>
		</ul>
		<% if user_signed_in? %>
		<%= render 'tweets/form', tweet: Tweet.new %>
		<% end %>

		<ul class="nav navbar-nav navbar-right">
			<li>
				<% if user_signed_in? %>
				<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
				<% else %>
				<%= link_to 'Sign In', new_user_session_path %>
				<% end %>
			</li>
		</ul>
  	</nav>
  	<div class="container">
    <%= yield %>
</div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true, class: 'navbar-form navbar-left') do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  
    <%= form.text_field :message, id: :tweet_message %>
    <%= form.hidden_field :user_id, id: :tweet_user_id, value: current_user.id %>
    <%= form.submit 'Chirp dat', class: 'btn btn-primary' %>
    
  </div>

<% end %>

app/views/tweets/_tweet.html.erb


<div class="well">
			<%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %>: 
			<% if tweet.created_at > 1.day.ago %>
				<%= time_ago_in_words tweet.created_at %> ago
				<% else %>
				<%= tweet.created_at.strftime('%b %d') %>
				<% end %>
	<p>
		<%= tweet.message.html_safe %>
	</p>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user.username %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user.username %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>